# Generated by Django 5.2.11 on 2026-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_ai_suggestions_resume_authenticity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_likelihood_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
