# Generated by Django 5.2.11 on 2026-03-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume_ai_likelihood_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='authenticity_score',
        ),
    ]
