# Generated by Django 5.2.11 on 2026-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_resume_authenticity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='integrity_score',
        ),
        migrations.AddField(
            model_name='resume',
            name='implicit_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
