# Generated by Django 5.2.11 on 2026-04-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_resume_integrity_score_resume_implicit_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ai_likelihood_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tone_score',
        ),
    ]
