# Generated by Django 5.2.11 on 2026-04-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_resume_ai_likelihood_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='implicit_skills',
        ),
    ]
